services:
  psql:
    image: postgres:latest
    container_name: psql
    environment:
      POSTGRES_USER: psqladmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasknotes
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d